package com.restapi.ToTheMoon;

public enum Constraints {
	INCUMBENT_PROTECTION,
	MAJORITY_MINORITY_DISTRICTS,
	POLSBY_POPPER_CONSTR,
	POPULATION_FATNESS_CONSTR,
	GRAPH_COMPACTNESS_CONSTR,
	TOTAL_POPULATION,
	POPULATION_CONSTR,
	TVAP,
	CVAP,
}
