package com.restapi.ToTheMoon;

public enum Measures {
	POPULATION_EQUALITY,
	SPLIT_COUNTIES,
	DEVIATION_FROM_AVG,
	DEVIATION_FROM_ENACTED_AREA,
	DEVIATION_FROM_ENACTED_POPULATION,
	POLSBY_POPPER_OBJ,
	POPULATION_FATNESS_OBJ,
	GRAPH_COMPACTNESS_OBJ,
	EFFICIENCY_GAP_OBJ,
}
